language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: QOUsvOr1Rg6mRUOK4BcAHv2biumpLfcM3nrE9XstECLDxJSkkYKDn7bX4n1fsY1H3tOHJfw7AULDdlUafifD8DPbQBF7zTqWknA2H/wY9LUa+agmYZqtE8+8/mhrX3rRkNFXdzzzYBvnaZ+YnvvhI+6N9xn117KbPkaNpN2U0wFvviEQ7+x/pS3dBXvDrchqYQv38ahcDr/v81vDI+uQtXneqsiDOuUNjD+tJKMex1Mid+mzIAg91zKaC4SqF7M5RpSe/IhxDkDe46lAFF/FCVObSqM8yNTRuZB5RoGgJMzskNzcMzEyiDKWibMlPobGvoiW+4SwGnOf7maOjGJJvCko8Yy9MT37fPg55UIiaz8e3SkauUkNEs5RGyKlAMmY4lJUNeXiMnSRMgWWilMy6lcXAdiZnKs0r8miJPexCnacsRHYpf8rviC7zEourQvshl9Ax87igW2HP10ejjrwNGDV4noEESR7QfzbcD3qsWZ/N++PnT0gnp54BZe57UToJO1u/4wNt+oeIbXg++kjbPvhSpu/c2PMJcu4wm4Paa1uTzd2YGnVmklSSR4Djhlsvy48H8F4cRsOQfBcqpPzEyfXFxU9Rj2e8PDhMd0f0iWqT+y7+1FVAp09Q7i5IH2WupNFdfZsQii4O3Dq4Zwmp+b/lcu4QuawnXZjkDKZi7M=
  app: first-travis-heroku
  on:
    repo: iPoplar/first-travis-heroku
